name: house_prices
channels: 
  - defaults
dependencies:
  - numpy
  - pandas
  - keras
  - matplotlib
  - seaborn
  - scikit-learn
  - tqdm
  - pandas-profiling
  - statsmodels
  - notebook=6.0.2
  - python=3.7.5